name: 'doc'
on:

  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  BTD:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '📓 BuildTheDocs'
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build